import express from 'express';
import path from 'node:path';
import archiver from 'archiver';
import sharp from 'sharp';
import { getJob } from '../services/jobManager.js';
import { sanitizeHeaderFilename, insertFilenameSuffix } from '../utils/paths.js';

const router = express.Router();

router.get('/:jobId/zip', (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: 'Job not found' });
    return;
  }
  const doneFiles = Array.from(job.files.values()).filter((f) => f.status === 'done' && f.compressedPath);
  if (doneFiles.length === 0) {
    res.status(400).json({ error: 'No compressed files are available yet for this job.' });
    return;
  }

  // The ZIP itself is renamed to flag a batch-wide dimension reduction
  // (e.g. "Premium_Laminates_3000px.zip") - but per the "never rename
  // images inside the output" rule, every file *inside* the archive keeps
  // its own original name/path untouched (see the archive.file() loop
  // below, which uses each file's untouched compressedRelativePath).
  const requestedMaxWidth = job.settings?.maxWidth || null;
  const anyResized = requestedMaxWidth && doneFiles.some((f) => f.result?.maxWidthApplied);
  const baseName = sanitizeHeaderFilename(job.label, `compressed-${job.id}`);
  const zipName = anyResized ? insertFilenameSuffix(`${baseName}.zip`, `${requestedMaxWidth}px`) : `${baseName}.zip`;

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${zipName}"`);

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.on('error', (err) => {
    // eslint-disable-next-line no-console
    console.error('Zip stream error:', err);
    res.destroy(err);
  });
  archive.pipe(res);

  for (const file of doneFiles) {
    archive.file(file.compressedPath, { name: file.compressedRelativePath });
  }

  archive.finalize();
});

router.get('/:jobId/:fileId', (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: 'Job not found' });
    return;
  }
  const file = job.files.get(req.params.fileId);
  if (!file || file.status !== 'done' || !file.compressedPath) {
    res.status(404).json({ error: 'Compressed file not available.' });
    return;
  }
  // The file stored on disk (and inside any ZIP) always keeps its original
  // name untouched - this suffix is applied only to the name offered for
  // this single, ad-hoc download, so a resized copy can't silently
  // overwrite an original of the same name sitting in the same downloads
  // folder (e.g. "001.jpg" -> "001_3000px.jpg").
  const baseFileName = path.basename(file.compressedRelativePath);
  const downloadName = file.result?.maxWidthApplied && file.result?.requestedMaxWidth
    ? insertFilenameSuffix(baseFileName, `${file.result.requestedMaxWidth}px`)
    : baseFileName;
  res.download(file.compressedPath, downloadName);
});

/**
 * On-the-fly, capped-size preview thumbnail for the before/after compare UI.
 * We deliberately never send the original 300-500MB source or even the full
 * compressed file to the browser just to render a preview - only a small
 * re-encoded JPEG, generated by Sharp on demand.
 */
router.get('/:jobId/:fileId/thumbnail/:variant', async (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) {
    res.status(404).end();
    return;
  }
  const file = job.files.get(req.params.fileId);
  if (!file) {
    res.status(404).end();
    return;
  }
  const { variant } = req.params;
  const sourcePath = variant === 'compressed' ? file.compressedPath : file.originalPath;
  if (!sourcePath) {
    res.status(404).end();
    return;
  }
  if (file.kind === 'pdf') {
    // PDFs get a dedicated document preview panel client-side instead of a
    // rendered thumbnail - rasterizing a PDF page reliably needs a codec
    // (pdfium/poppler) that isn't guaranteed to be present in every Sharp
    // build across deployment environments, so we don't depend on it.
    res.status(404).end();
    return;
  }

  try {
    const buffer = await sharp(sourcePath, { sequentialRead: true, limitInputPixels: false })
      .rotate()
      .resize({ width: 640, height: 640, fit: 'inside', withoutEnlargement: true })
      .jpeg({ quality: 72 })
      .toBuffer();
    res.setHeader('Content-Type', 'image/jpeg');
    res.setHeader('Cache-Control', 'private, max-age=3600');
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ error: 'Could not generate preview.' });
  }
});

export default router;
