import express from 'express';
import path from 'node:path';
import archiver from 'archiver';
import sharp from 'sharp';
import { getJob } from '../services/jobManager.js';

const router = express.Router();

router.get('/:jobId/zip', (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: 'Job not found' });
    return;
  }
  const doneFiles = Array.from(job.files.values()).filter((f) => f.status === 'done' && f.compressedPath);
  if (doneFiles.length === 0) {
    res.status(400).json({ error: 'No compressed files are available yet for this job.' });
    return;
  }

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="compressed-${job.id}.zip"`);

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.on('error', (err) => {
    // eslint-disable-next-line no-console
    console.error('Zip stream error:', err);
    res.destroy(err);
  });
  archive.pipe(res);

  for (const file of doneFiles) {
    archive.file(file.compressedPath, { name: file.compressedRelativePath });
  }

  archive.finalize();
});

router.get('/:jobId/:fileId', (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: 'Job not found' });
    return;
  }
  const file = job.files.get(req.params.fileId);
  if (!file || file.status !== 'done' || !file.compressedPath) {
    res.status(404).json({ error: 'Compressed file not available.' });
    return;
  }
  res.download(file.compressedPath, path.basename(file.compressedRelativePath));
});

/**
 * On-the-fly, capped-size preview thumbnail for the before/after compare UI.
 * We deliberately never send the original 300-500MB source or even the full
 * compressed file to the browser just to render a preview - only a small
 * re-encoded JPEG, generated by Sharp on demand.
 */
router.get('/:jobId/:fileId/thumbnail/:variant', async (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) {
    res.status(404).end();
    return;
  }
  const file = job.files.get(req.params.fileId);
  if (!file) {
    res.status(404).end();
    return;
  }
  const { variant } = req.params;
  const sourcePath = variant === 'compressed' ? file.compressedPath : file.originalPath;
  if (!sourcePath) {
    res.status(404).end();
    return;
  }
  if (file.kind === 'pdf') {
    // PDFs get a dedicated document preview panel client-side instead of a
    // rendered thumbnail - rasterizing a PDF page reliably needs a codec
    // (pdfium/poppler) that isn't guaranteed to be present in every Sharp
    // build across deployment environments, so we don't depend on it.
    res.status(404).end();
    return;
  }

  try {
    const buffer = await sharp(sourcePath, { sequentialRead: true, limitInputPixels: false })
      .rotate()
      .resize({ width: 640, height: 640, fit: 'inside', withoutEnlargement: true })
      .jpeg({ quality: 72 })
      .toBuffer();
    res.setHeader('Content-Type', 'image/jpeg');
    res.setHeader('Cache-Control', 'private, max-age=3600');
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ error: 'Could not generate preview.' });
  }
});

export default router;
