import { useCallback, useRef, useState } from 'react';

/**
 * A drag-to-reveal before/after slider. Both images are small, on-the-fly
 * thumbnails generated by the server (see /api/download/.../thumbnail/...)
 * - never the full-size original or compressed file - so this stays cheap
 * even for 300-500MB sources.
 */
export default function CompareSlider({ beforeSrc, afterSrc }) {
  const [position, setPosition] = useState(50);
  const [containerWidth, setContainerWidth] = useState(0);
  const containerRef = useRef(null);
  const dragging = useRef(false);

  const measure = useCallback((node) => {
    containerRef.current = node;
    if (node) setContainerWidth(node.offsetWidth);
  }, []);

  const updateFromClientX = useCallback((clientX) => {
    const el = containerRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const pct = ((clientX - rect.left) / rect.width) * 100;
    setPosition(Math.max(0, Math.min(100, pct)));
  }, []);

  const onPointerDown = (e) => {
    dragging.current = true;
    updateFromClientX(e.clientX);
    e.currentTarget.setPointerCapture?.(e.pointerId);
  };
  const onPointerMove = (e) => {
    if (!dragging.current) return;
    updateFromClientX(e.clientX);
  };
  const onPointerUp = () => { dragging.current = false; };

  return (
    <div
      ref={measure}
      className="compare-slider"
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      onPointerLeave={onPointerUp}
      role="slider"
      aria-label="Before and after comparison"
      aria-valuenow={Math.round(position)}
      aria-valuemin={0}
      aria-valuemax={100}
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'ArrowLeft') setPosition((p) => Math.max(0, p - 5));
        if (e.key === 'ArrowRight') setPosition((p) => Math.min(100, p + 5));
      }}
    >
      <img src={beforeSrc} alt="Original" draggable={false} />
      <div className="after-wrap" style={{ width: `${position}%` }}>
        <img src={afterSrc} alt="Compressed" draggable={false} style={{ width: containerWidth || '100%' }} />
      </div>
      <div className="compare-handle" style={{ left: `${position}%` }} />
      <span className="compare-label before">Before</span>
      <span className="compare-label after">After</span>
    </div>
  );
}
